version: '3.6'

services:
    web:
        image: web-dev
        build: 
            context: ./web
            dockerfile: Dockerfile.dev
        ports: 
            - '80:3000'
        volumes:
            - ./web/src:/app/src